format = """
[ $os](bg:4 fg:0)\
[î‚°](bg:12 fg:4)\
$directory\
[î‚°](fg:12 bg:13)\
$git_branch\
$git_status\
[î‚°](fg:13 bg:2)\
$nodejs\
$rust\
$golang\
$php\
[î‚°](fg:2 bg:14)\
$custom\
[î‚° ](fg:14)\
$cmd_duration\
\n$character"""

[character]
success_symbol = '[â¯](2)'
error_symbol = '[â¯](9)'

[directory]
style = "fg:0 bg:12"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"

[cmd_duration]
min_time = 3500
format = '[$duration](3 bold)'

[os]
format = "[[$symbol](bg:4 fg:0)]($style)"
style = "bg:4"
disabled = false

[os.symbols]
AlmaLinux = "ïŒ "
Alpine = "ïŒ€ "
Amazon = "ï‰° "
Android = "îœ "
Arch = "ó°£‡ "
Artix = "ó°£‡ "
CentOS = "ïŒ„ "
Debian = "î½ "
DragonFly = "î»¸ "
EndeavourOS = "ïŒ¢ "
Fedora = "î½† "
FreeBSD = "ïŠ "
Garuda = "ïŒ· "
Gentoo = "ó°£¨ "
Illumos = "ïŒ¦ "
Kali = "ïŒ§ "
Linux = "îœ’ "
Macos = "îœ‘ "
Manjaro = "ïŒ’ "
Mint = "ó°£­ "
NixOS = "ó±„… "
OpenBSD = "ïŒ¨ "
openEuler = "ó°’ "
openSUSE = "î½­ "
Pop = "ïŒª "
Raspbian = "îœ¢ "
Redhat = "î½ "
RedHatEnterprise = "î½ "
RockyLinux = "ïŒ« "
Solus = "ïŒ­ "
SUSE = "î½­ "
Ubuntu = "î½² "
Unknown = "ï„¨ "
Void = "ïŒ®  "
Windows = "îœ "

[git_branch]
symbol = "ï˜"
style = "bg:13"
format = '[[ $symbol $branch ](fg:0 bg:13)]($style)'

[git_status]
style = "bg:13"
format = '[[($all_status$ahead_behind )](fg:0 bg:13)]($style)'

[nodejs]
symbol = "î´"
format = '[[ $symbol ($version)](fg:0 bg:2)]($style)'

[bun]
symbol = "ğŸ"
style = "bg:2"
format = '[[ $symbol ($version)](fg:0 bg:2)]($style)'

[rust]
symbol = "îš‹"
style = "bg:2"
format = '[[ $symbol ($version)](fg:0 bg:2)]($style)'

[golang]
symbol = "î˜§"
style = "bg:2"
format = '[[ $symbol ($version)](fg:0 bg:2)]($style)'

[php]
symbol = "î˜ˆ"
style = "bg:2"
format = '[[ $symbol ($version)](fg:0 bg:2)]($style)'

[custom.tailscale]
symbol = "ó°ˆº"
format = "[[ $symbol Tailscale ](fg:0 bg:14)]($style)"
style = "(fg:0 bg:6)"
when = "tailscale status | grep -q 'Tailscale is stopped.' && exit 1 || exit 0"

# [custom.wireguard]
# command = "wg show interfaces"
# symbol = "î»¸"
# format = "[[ $symbol $output ](fg:0 bg:6)]($style)"
# style = "bg:6"
# when = "wg show interfaces | grep -q . && exit 0 || exit 1"

[time]
disabled = false
time_format = "%.3f" # Hour:Minute Format
style = "bg:1"
format = '[[ $time ](fg:0 bg:1)]($style)'