---
# 1Password installation for Debian/Ubuntu

- name: Add 1Password GPG key
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg
    state: present
  become: true

- name: Add 1Password repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/amd64 stable main"
    filename: 1password
    state: present
  become: true

- name: Install 1Password
  ansible.builtin.apt:
    name:
      - 1password
      - 1password-cli
    state: present
    update_cache: true
  become: true
